import { t } from './stores/i18n'
import type { Character } from './types'

export default {
    name: t('default.name'),
    level: 1,
    lineages: t('default.lineages'),
    classes: t('default.classes'),
    attributes: {
        str: 10,
        dex: 10,
        con: 10,
        int: 10,
        wis: 10,
        cha: 10,
    },
    mechanics: {
        hitPoints: {
            total: 0,
            current: 0,
            temporary: 0,
            debuff: 0,
        },
        bonusInitiative: 0,
        defense: 10,
        walkSpeed: 30,
        climbSpeed: 0,
        swimSpeed: 0,
        flySpeed: 0,
        darkVision: 0,
        other: [],
    },
    weapons: t('default.weapons'),
    armors: t('default.armors'),
    languages: t('default.languages'),
    skills: [
        { name: t('default.skills.save'), attribute: 'str', proficiency: false, expertise: false, otherBonus: 0 },
        { name: t('default.skills.athletics'), attribute: 'str', proficiency: false, expertise: false, otherBonus: 0 },
        { name: t('default.skills.save'), attribute: 'dex', proficiency: false, expertise: false, otherBonus: 0 },
        { name: t('default.skills.acrobatics'), attribute: 'dex', proficiency: false, expertise: false, otherBonus: 0 },
        { name: t('default.skills.stealth'), attribute: 'dex', proficiency: false, expertise: false, otherBonus: 0 },
        {
            name: t('default.skills.sleightOfHand'),
            attribute: 'dex',
            proficiency: false,
            expertise: false,
            otherBonus: 0,
        },
        { name: t('default.skills.save'), attribute: 'con', proficiency: false, expertise: false, otherBonus: 0 },
        { name: t('default.skills.save'), attribute: 'int', proficiency: false, expertise: false, otherBonus: 0 },
        { name: t('default.skills.arcana'), attribute: 'int', proficiency: false, expertise: false, otherBonus: 0 },
        { name: t('default.skills.history'), attribute: 'int', proficiency: false, expertise: false, otherBonus: 0 },
        {
            name: t('default.skills.investigation'),
            attribute: 'int',
            proficiency: false,
            expertise: false,
            otherBonus: 0,
        },
        { name: t('default.skills.nature'), attribute: 'int', proficiency: false, expertise: false, otherBonus: 0 },
        { name: t('default.skills.religion'), attribute: 'int', proficiency: false, expertise: false, otherBonus: 0 },
        { name: t('default.skills.save'), attribute: 'wis', proficiency: false, expertise: false, otherBonus: 0 },
        { name: t('default.skills.insight'), attribute: 'wis', proficiency: false, expertise: false, otherBonus: 0 },
        {
            name: t('default.skills.animalHandling'),
            attribute: 'wis',
            proficiency: false,
            expertise: false,
            otherBonus: 0,
        },
        { name: t('default.skills.medicine'), attribute: 'wis', proficiency: false, expertise: false, otherBonus: 0 },
        { name: t('default.skills.perception'), attribute: 'wis', proficiency: false, expertise: false, otherBonus: 0 },
        { name: t('default.skills.survival'), attribute: 'wis', proficiency: false, expertise: false, otherBonus: 0 },
        { name: t('default.skills.save'), attribute: 'cha', proficiency: false, expertise: false, otherBonus: 0 },
        {
            name: t('default.skills.performance'),
            attribute: 'cha',
            proficiency: false,
            expertise: false,
            otherBonus: 0,
        },
        { name: t('default.skills.persuasion'), attribute: 'cha', proficiency: false, expertise: false, otherBonus: 0 },
        { name: t('default.skills.deception'), attribute: 'cha', proficiency: false, expertise: false, otherBonus: 0 },
        {
            name: t('default.skills.intimidation'),
            attribute: 'cha',
            proficiency: false,
            expertise: false,
            otherBonus: 0,
        },
    ],
    tools: [],
    resources: {
        coins: {
            copper: 0,
            silver: 0,
            gold: 0,
            platinum: 0,
        },
        recoverable: [],
        finite: [],
    },
    attacks: [
        {
            name: t('default.attacks.unarmed'),
            addProficiency: true,
            attribute: 'str',
            hitBonus: 0,
            damageBonus: 0,
            damage: '1',
            damageType: 'contundente',
            notes: '',
            source: '',
        },
    ],
    features: [],
    spellMechanics: {
        attribute: 'int',
        hitBonus: 0,
        availablePerDay: 0,
        saveDifficultyBonus: 0,
        slots: [],
    },
    spells: [],
} as Character
