export default {
  name: "Alû",
  level: 4,
  lineages: "Leonin",
  classes: "Rogue 1 / Paladin 3",

  // attributes: {
  //   str: 13,
  //   con: 16,
  //   dex: 14,
  //   int: 8,
  //   wis: 11,
  //   cha: 14,
  // },

  // mechanics: [
  //   { name: "Vida Total",      value: 37 },
  //   { name: "Vida Atual",      value: 37 },
  //   { name: "Vida Temp.",      value: 0 },
  //   { name: "Debuff Vida",     value: 0 },
  //   { name: "Iniciative",      value: 3  },
  //   { name: "Defesa",          value: 16 },
  //   { name: "Movimento",       value: 30 },
  //   { name: "Voar",            value: "Igual" },
  //   { name: "Nadar",           value: "Igual" },
  //   { name: "Visão no Escuro", value: 60 },
  //   { name: "Resistência",     value: "Veneno" },
  //   { name: "Imunidade",       value: "Sono Mágico" },
  //   { name: "Vantagem SG",     value: "Doenças" },
  //   { name: "Vantagem SG",     value: "Veneno" },
  //   { name: "Vantagem SG",     value: "Morte"},
  // ],

  // skills: [
  //   { name: "Salvaguarda",       attribute: "str", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Atletismo",         attribute: "str", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Salvaguarda",       attribute: "dex", proficiency: true,  expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Acrobacia",         attribute: "dex", proficiency: true,  expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Furtividade",       attribute: "dex", proficiency: true,  expertise: true,  otherBonus: 0, notes: "", source: "" },
  //   { name: "Prestidigitação",   attribute: "dex", proficiency: true,  expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Salvaguarda",       attribute: "con", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Salvaguarda",       attribute: "int", proficiency: true,  expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Arcanismo",         attribute: "int", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "História",          attribute: "int", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Investigação",      attribute: "int", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Natureza",          attribute: "int", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Religião",          attribute: "int", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Salvaguarda",       attribute: "wis", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Intuição",          attribute: "wis", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Lidar com Animais", attribute: "wis", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Medicina",          attribute: "wis", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Percepção",         attribute: "wis", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Sobrevivência",     attribute: "wis", proficiency: true,  expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Salvaguarda",       attribute: "cha", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Atuação",           attribute: "cha", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Persuasão",         attribute: "cha", proficiency: false, expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Enganação",         attribute: "cha", proficiency: true,  expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Intimidação",       attribute: "cha", proficiency: true,  expertise: false, otherBonus: 0, notes: "", source: "" },
  //   { name: "Ladinos",           attribute: "kit", proficiency: true,  expertise: true,  otherBonus: 0, notes: "", source: "" },
  //   { name: "Venenos",           attribute: "kit", proficiency: true,  expertise: false, otherBonus: 0, notes: "", source: "" },
  // ],

  // recoverable_resources: [
  //   { name: "d8",                        current: 1,  total: 1,  recoveredBy: "long",  notes: "", source: "" },
  //   { name: "d10",                       current: 1,  total: 3,  recoveredBy: "long",  notes: "", source: "" },
  //   { name: 'Canalizar Divino',          current: 1,  total: 1,  recoveredBy: "short", notes: "", source: "" },
  //   { name: "Magias 1o círculo",         current: 3,  total: 3,  recoveredBy: "long",  notes: "", source: "" },
  //   { name: 'Absorver Canalizar Divino', current: 0,  total: 1,  recoveredBy: "long",  notes: "", source: "" },
  //   { name: 'Senso Divino',              current: 3,  total: 3,  recoveredBy: "long",  notes: "", source: "" },
  //   { name: 'Curar pelas Mãos',          current: 15, total: 15, recoveredBy: "long",  notes: "", source: "" },
  //   { name: 'Lágrima da Dríade',         current: 1,  total: 1,  recoveredBy: "long",  notes: "", source: "" },
  // ],

  // finite_resources: [
  //   { name: "Rede",                                amount: 1,  unity: "u", notes: "", source: "https://www.dndbeyond.com/equipment/net"},
  //   { name: "Veneno Potente",                      amount: 1,  unity: "u", notes: "", source: ""},
  //   { name: "Adaga com Prata",                     amount: 1,  unity: "u", notes: "", source: ""},
  //   { name: "Adagas",                              amount: 5,  unity: "u", notes: "", source: ""},
  //   { name: "Cura 1d4+1",                          amount: 1,  unity: "u", notes: "", source: ""},
  //   { name: "Cura 2d4+2",                          amount: 1,  unity: "u", notes: "", source: ""},
  //   { name: "Bomba de Fumaça",                     amount: 2,  unity: "u", notes: "", source: "https://www.dndbeyond.com/equipment/grenade-smoke"},
  //   { name: "Seixos",                              amount: 6,  unity: "u", notes: "", source: ""},
  //   { name: "Cadeado de alta qualidade com chave", amount: 1,  unity: "u", notes: "", source: ""},
  //   { name: "Algemas",                             amount: 2,  unity: "u", notes: "", source: "https://www.dndbeyond.com/equipment/manacles"},
  //   { name: "Corda de Cânhamo",                    amount: 15, unity: "m", notes: "", source: "https://www.dndbeyond.com/equipment/rope-hempen-50-feet"},
  //   { name: "Corrente",                            amount: 3,  unity: "m", notes: "", source: ""},
  //   { name: "Kit Primeiro Socorros",               amount: 10, unity: "u", notes: "", source: "https://www.dndbeyond.com/equipment/healers-kit"},
  //   { name: "Óleo",                                amount: 3,  unity: "u", notes: "", source: "https://www.dndbeyond.com/equipment/oil-flask"},
  //   { name: "Vela",                                amount: 5,  unity: "u", notes: "", source: ""},
  //   { name: "Apito",                               amount: 1,  unity: "u", notes: "", source: ""},
  //   { name: "Linha de Seda",                       amount: 15, unity: "m", notes: "", source: ""},
  //   { name: "Frascos",                             amount: 1, unity: "u",  notes: "", source: ""},
  //   { name: "Caixa de Fogo",                       amount: 1, unity: "u",  notes: "", source: ""},
  //   { name: "Bolsa com Giz",                       amount: 1, unity: "u",  notes: "", source: ""},
  //   { name: "Lanterna Coberta",                    amount: 1, unity: "u",  notes: "", source: "https://www.dndbeyond.com/equipment/lantern-hooded"},
  //   { name: "Livreto 50p.",                        amount: 1, unity: "u",  notes: "", source: ""},
  //   { name: "Lápis",                               amount: 1, unity: "u",  notes: "", source: ""},
  //   { name: "Parafina",                            amount: 1, unity: "u",  notes: "", source: ""},
  //   { name: "Pedra de Amolar",                     amount: 1, unity: "u",  notes: "", source: ""},
  //   { name: "Sino",                                amount: 1, unity: "u",  notes: "", source: ""},
  //   { name: "Insígnia Sagrada",                    amount: 1, unity: "u",  notes: "", source: ""},
  // ],

  // equipped_items: [
  //   { name: "Botas Élficas",              notes: "", source: "" },
  //   { name: "Manto Preto Comum",          notes: "", source: "" },
  //   { name: "Armadura de Couro Batido",   notes: "", source: "" },
  //   { name: "Lâmina Escondida com prata", notes: "", source: "" },
  //   { name: "Lâmina Escondida",           notes: "", source: "" },
  //   { name: "Mochila",                    notes: "", source: "" },
  // ],

  // coins: {
  //   copper:   10,
  //   silver:   24,
  //   gold:     389,
  //   platinum: 0,
  // },

  // attacks: [
  // ],

  // features: [
  //   {
  //     name: "Natureza Morte",
  //     description: "Você não precisa comer, beber ou respirar.\n\nVocê não precisa dormir e a magia não pode fazer você dormir. Você pode terminar um descanso longo em 4 horas se passar essas horas em um estado inativo e imóvel, durante o qual retém a consciência.",
  //     notes: "",
  //     source: ""
  //   },
  // ],
  // magic_mechanics: [
  //   { name: "bonusAttack",  value: 37 },
  //   { name: "memoMagic",    value: 16 },
  //   { name: "defenseMagic", value: 16 },
  // ],
  // magic: [
  // ],
}
